name: Publish NuGet Package To GitHub

on:
  push:
    tags:
      - 'v*.*.*' # Specify the tag pattern, e.g., 'v1.0.0'
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  # Adjust based on your project's .NET version

      - name: Determine Version
        id: determine_version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=${GITHUB_REF##*/}
            VERSION=${VERSION#v}
          else
            VERSION=${{ inputs.version }}
          fi
          if [[ -z "$VERSION" ]]; then
            echo "Version is required for manual runs. Exiting."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Add source
        run: dotnet nuget add source --username gregyjames --password ${{ secrets.GH_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gregyjames/index.json"
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release /p:Version=${{ env.VERSION }} /p:AssemblyVersion=${{ env.VERSION }}

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./output /p:Version=${{ env.VERSION }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./output/*.nupkg --source "github" --api-key "${{ secrets.GH_PAT }}"
        env:
          NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: "true"
