name: Publish NuGet Package To Github

on:
  push:
    tags:
      - 'v*.*.*' # Specify the tag pattern, e.g., 'v1.0.0'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  # Adjust based on your project's .NET version

      - name: Add source
        run: dotnet nuget add source --username gregyjames --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gj.autofac.caching.redis/index.json"
      
      - name: Set VERSION variable from tag
        run: |
          $VERSION=$Env:GITHUB_REF_NAME.TrimStart("v")
          echo "VERSION=$VERSION" >> $Env:GITHUB_ENV
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release /p:Version=$Env:VERSION /p:AssemblyVersion=$Env:VERSION

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./output

      - name: Publish to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
        env:
          NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: "true"
